docs: fix typos in README.md
Kotlin/kotlinx-datetime pull request #328
Opened 2023-12-02 12:21 UTC by EchoEllet

Just fixing a few typos in the `README.md`

2023-12-05 17:07 UTC, ilya-g requested changes

2023-12-05 17:07 UTC, ilya-g commented on README.md
> -# kotlinx-datetime
This is the name of the library, please leave it like this

2023-12-05 17:07 UTC, ilya-g commented on README.md
> +The library is published by Maven Central.
Maven Central is not a publisher, it's a place where artifacts are available.

2024-01-22 12:21 UTC, ellet0 commented
Hi @ilya-g, should this be merged or rejected?

2024-01-22 21:55 UTC, ilya-g requested changes

2024-01-22 21:55 UTC, ilya-g commented on README.md
> +time components are being added to date at compile time.
"a date" here means "an instance of LocalDate type"

2024-01-22 21:55 UTC, ilya-g commented on README.md
> +- In multiplatform projects, add a dependency to the `commonMain` source set of dependencies
It's the `dependencies` DSL block of a source set, not a set of dependencies.

2024-01-22 21:55 UTC, ilya-g commented on README.md
> +Gradle will try to find it among the installed JDKs or [provision](https://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning) automatically if it can't be found.
Better to reword as "[download] it automatically"

2025-10-21 12:17 UTC, dkhalanskyjb commented
Closed in favor of https://github.com/Kotlin/kotlinx-datetime/pull/578

2025-10-21 12:17 UTC, closed without merging

2025-10-21 12:23 UTC, EchoEllet commented
Apologies for not responding earlier, I haven't received notification at the time.