Provide custom serializers based on DateTimeFormat
Kotlin/kotlinx-datetime pull request #415
Opened 2024-07-23 13:37 UTC by dkhalanskyjb

The names of the serializers are still under discussion, but it's already decided that the serializers are going to be abstract classes.

Fixes #350

2025-05-27 17:33 UTC, ilya-g requested changes

2025-05-27 17:33 UTC, ilya-g commented on core/common/src/serializers/InstantSerializers.kt
> +        PrimitiveSerialDescriptor("kotlinx.datetime.Instant ISO", PrimitiveKind.STRING)
While there are no apparent restrictions on what can be used as a serial name, and no recommendations how to name multiple alternate serializers for the same type, this name may be used in error messages without quotes, so I think it would be better not to use spaces, so it can be read as one word.
Perhaps a slash can be used? E.g. `kotlinx.datetime.Instant/ISO` and `kotlinx.datetime.Instant/components`
Or have we already come to a decision about the current serial descriptor naming scheme?

2025-05-28 08:26 UTC, dkhalanskyjb commented on core/common/src/serializers/InstantSerializers.kt
> +        PrimitiveSerialDescriptor("kotlinx.datetime.Instant ISO", PrimitiveKind.STRING)
I do remember that we have explicitly (but arbitrarily!) chosen spaces, yes, but the point about error messages was not raised at the time. The naming scheme you propose looks good.

2025-05-28 17:09 UTC, ilya-g approved these changes

2025-05-28 17:09 UTC, ilya-g commented on core/common/src/serializers/InstantSerializers.kt
> + * The [SerialDescriptor.serialName] of the resulting serializer is `kotlinx.datetime.Instant serializer `[name].
Please update in docs of abstract serializers as well

2025-05-30 09:03 UTC, merged